# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default
  #vmImage: ubuntu-latest

stages:

  - stage: Install
    jobs: 
      - job: Install_tf
        steps:
        - task: CmdLine@2
          inputs:
            script: 'sudo apt install unzip'
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'


  - stage: Initialize
    jobs: 
      - job: Initialize
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'ado'
            backendAzureRmResourceGroupName: 'terraform-storage-rg'
            backendAzureRmStorageAccountName: 'terraformtfstateversion'
            backendAzureRmContainerName: 'terraformstate'
            backendAzureRmKey: 'project.terraform.tfstate'

  - stage: tf_validate
    jobs: 
      - job: Validate
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'validate'

